[server]
address = "127.0.0.1"
headless = true
maxUploadSize = 20
[browser]
gatherUsageStats = false
[theme]
primaryColor = "#a5442a"
backgroundColor = "#faf8f3"
secondaryBackgroundColor = "#eeeae1"
textColor = "#252a2b"
font = "sans serif"
